try {

} catch () {

} finally {

}


try{}catch(){}finally{}


try {
    'block'
} catch (err) {
    'block'
} finally {
    'block'
}
